
TARGET = cpl
$(TARGET):

###include makedefs
CFILES = \
	cpl.c	   \
	cplask.c   \
	cplmask.c  \
	cplparam.c \
	cplload.c  \
	cplmpar.c  \
	cplsetup.c \
	cplinit.c

HDRS = \
	cpldefs.h  \
	cplext.h   \
	cplinit.h  \
	cplitf.h   \
	wrapper.h

SPICE_VERSION = NGSPICE=42

include ../Make2
