
TARGET = vcvs
$(TARGET):

###include makedefs
CFILES = \
	vcvs.c		\
	vcvsask.c	\
	vcvsfbr.c	\
	vcvsinit.c	\
	vcvsload.c	\
	vcvspar.c	\
	vcvspzld.c	\
	vcvssacl.c	\
	vcvsset.c	\
	vcvssld.c	\
	vcvssprt.c	\
	vcvssset.c


HDRS = \
	vcvsdefs.h	\
	vcvsext.h	\
	vcvsinit.h	\
	vcvsitf.h	\
	wrapper.h


include ../Make2
