
TARGET = vccs
$(TARGET):

###include makedefs
CFILES = \
	vccs.c		\
	vccsask.c	\
	vccsinit.c	\
	vccsload.c	\
	vccspar.c	\
	vccspzld.c	\
	vccssacl.c	\
	vccsset.c	\
	vccssld.c	\
	vccssprt.c	\
	vccssset.c

HDRS = \
	vccsdefs.h	\
	vccsext.h	\
	vccsinit.h	\
	vccsitf.h	\
	wrapper.h


include ../Make2
