
TARGET = vbic
$(TARGET):

###include makedefs
CFILES = \
	vbic.c		\
	vbicacld.c	\
	vbicask.c	\
	vbicconv.c	\
	vbicgetic.c	\
	vbicinit.c	\
	vbicload.c	\
	vbicmask.c	\
	vbicmpar.c	\
	vbicnoise.c	\
	vbicparam.c	\
	vbicpzld.c	\
	vbicsetup.c	\
	vbicsoachk.c \
	vbictemp.c	\
	vbictrunc.c

HDRS = \
	vbicdefs.h	\
	vbicext.h	\
	vbicinit.h	\
	vbicitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE=42

include ../Make2
