
GNUCAP = gnucap
# TODO: load with wildcard.
# BUG: depends on attach order.
GNUCAP_ARGS = -a ../mos1 -a ../bsim1 -a ../bsim2 -a ../dio -a ../jfet -a ../bjt
# -a ../vbic -a ../bjt -a ../jfet -a ../bsim2 -a ../bsim1 -a ../mes \
# 				  -a ../mesa -a ../hfet1 -a ../hfet2

include ../../Make.test

.PHONY: check
