
TARGET = mes
$(TARGET):

###include makedefs
CFILES = \
	mes.c		\
	mesacl.c	\
	mesask.c	\
	mesdisto.c	\
	mesdset.c	\
	mesgetic.c	\
	mesinit.c	\
	mesload.c	\
	mesmask.c	\
	mesmpar.c	\
	mesnoise.c	\
	mesparam.c	\
	mespzld.c	\
	messetup.c	\
	mestemp.c	\
	mestrunc.c

HDRS = \
	mesdefs.h	\
	mesext.h	\
	mesinit.h	\
	mesitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE=42

include ../Make2
