
TARGET = urc
$(TARGET):

###include makedefs
CFILES = \
	urc.c		\
	urcask.c	\
	urcinit.c	\
	urcmask.c	\
	urcmpar.c	\
	urcparam.c	\
	urcsetup.c

HDRS = \
	urcdefs.h	\
	urcext.h	\
	urcinit.h	\
	urcitf.h	\
	wrapper.h


include ../Make2
