
TARGET = tra
$(TARGET):

###include makedefs
CFILES = \
	tra.c		\
	traacct.c	\
	traacld.c	\
	traask.c	\
	trainit.c	\
	traload.c	\
	traparam.c	\
	trasetup.c	\
	tratemp.c	\
	tratrunc.c

HDRS = \
	tradefs.h	\
	traext.h	\
	trainit.h	\
	traitf.h	\
	wrapper.h


include ../Make2
