
TARGET = csw
$(TARGET):

###include makedefs
CFILES = \
	csw.c		\
	cswacld.c	\
	cswask.c	\
	cswinit.c	\
	cswload.c	\
	cswmask.c	\
	cswmpar.c	\
	cswnoise.c	\
	cswparam.c	\
	cswpzld.c	\
	cswsetup.c	\
	cswtrunc.c 

HDRS = \
	cswdefs.h	\
	cswext.h	\
	cswinit.h	\
	cswitf.h	\
	wrapper.h


include ../Make2
