
TARGET = vsrc
$(TARGET):

###include makedefs
CFILES = \
	vsrc.c		\
	vsrcacct.c	\
	vsrcacld.c	\
	vsrcask.c	\
	vsrcdel.c	\
	vsrcfbr.c	\
	vsrcinit.c	\
	vsrcload.c	\
	vsrcpar.c	\
	vsrcpzld.c	\
	vsrcpzs.c	\
	vsrcset.c	\
	vsrctemp.c

HDRS = \
	vsrcdefs.h	\
	vsrcext.h	\
	vsrcinit.h	\
	vsrcitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE=42

include ../Make2
