
TARGET = cap
$(TARGET):

###include makedefs
CFILES = \
	cap.c		\
	capacld.c	\
	capask.c	\
	capgetic.c	\
	capinit.c	\
	capload.c	\
	capmask.c	\
	capmpar.c	\
	capparam.c	\
	cappzld.c	\
	capsacl.c	\
	capsetup.c	\
	capsload.c	\
	capsprt.c	\
	capsset.c	\
	capsupd.c	\
	captemp.c	\
	captrunc.c

HDRS = \
	capdefs.h	\
	capext.h	\
	capinit.h	\
	capitf.h	\
	wrapper.h


include ../Make2
