
TARGET = asrc
$(TARGET):

###include makedefs
CFILES = \
	asrc.c		\
	asrcacld.c	\
	asrcask.c	\
	asrcconv.c	\
	asrcdel.c	\
	asrcdest.c	\
	asrcfbr.c	\
	asrcinit.c	\
	asrcload.c	\
	asrcpar.c	\
	asrcpzld.c	\
	asrcset.c   \
	asrctemp.c

HDRS = \
	asrcdefs.h	\
	asrcext.h	\
	asrcitf.h	\
	asrcinit.h	\
	wrapper.h

SPICE_VERSION = NGSPICE=42

include ../Make2
