
TARGET = ccvs
$(TARGET):

###include makedefs
CFILES = \
	ccvs.c		\
	ccvsask.c	\
	ccvsfbr.c	\
	ccvsinit.c	\
	ccvsload.c	\
	ccvspar.c	\
	ccvspzld.c	\
	ccvssacl.c	\
	ccvsset.c	\
	ccvssld.c	\
	ccvssprt.c	\
	ccvssset.c

HDRS = \
	ccvsdefs.h	\
	ccvsext.h	\
	ccvsinit.h	\
	ccvsitf.h	\
	wrapper.h


include ../Make2
