
TARGET = jfet
$(TARGET):

###include makedefs
CFILES = \
	jfet.c		\
	jfetacld.c	\
	jfetask.c	\
	jfetdist.c	\
	jfetdset.c	\
	jfetic.c	\
	jfetinit.c	\
	jfetload.c	\
	jfetmask.c	\
	jfetmpar.c	\
	jfetnoi.c	\
	jfetpar.c	\
	jfetpzld.c	\
	jfetset.c	\
	jfettemp.c	\
	jfettrun.c

HDRS = \
	jfetdefs.h	\
	jfetext.h	\
	jfetinit.h	\
	jfetitf.h	\
	wrapper.h

SPICE_VERSION = NGSPICE=42

include ../Make2
