
TARGET = isrc
$(TARGET):

###include makedefs
CFILES = \
	isrc.c		\
	isrcacct.c	\
	isrcacld.c	\
	isrcask.c	\
	isrcinit.c	\
	isrcload.c	\
	isrcpar.c	\
	isrctemp.c

HDRS = \
	isrcdefs.h	\
	isrcext.h	\
	isrcinit.h	\
	isrcitf.h	\
	wrapper.h


include ../Make2
